(()=>{
'use strict';
const $=id=>document.getElementById(id);
const canvas=$('cellCanvas'),ctx=canvas.getContext('2d'),viewer=$('viewer');
const C={corner:'#2476d2',face:'#f39a32',body:'#d94b8c',central:'#f0b429',neighbor:'#25a6a1',void:'#7c3aed',na:'#8b5cf6',cl:'#35a85b',cs:'#e0528d',zn:'#5479d8',s:'#e6a326',po:'#597fd3',fe:'#d15184',cu:'#dc7b32'};

const cubeCorners=(h=1)=>[-1,1].flatMap(x=>[-1,1].flatMap(y=>[-h,h].map(z=>({p:[x,y,z],type:'corner'}))));
const cubeEdges=(h=1)=>{const v=cubeCorners(h).map(a=>a.p),e=[];for(let i=0;i<v.length;i++)for(let j=i+1;j<v.length;j++){let d=0;for(let k=0;k<3;k++)if(v[i][k]!==v[j][k])d++;if(d===1)e.push([v[i],v[j]])}return e};
const faceAtoms=[[-1,0,0],[1,0,0],[0,-1,0],[0,1,0],[0,0,-1],[0,0,1]].map(p=>({p,type:'face'}));
function hexGeometry(){const top=[],bottom=[];for(let i=0;i<6;i++){const a=Math.PI/3*i;top.push([Math.cos(a),Math.sin(a),.82]);bottom.push([Math.cos(a),Math.sin(a),-.82])}const atoms=[...top,...bottom].map(p=>({p,type:'corner'}));atoms.push({p:[0,0,.82],type:'face'},{p:[0,0,-.82],type:'face'});const edges=[];for(let i=0;i<6;i++)edges.push([top[i],top[(i+1)%6]],[bottom[i],bottom[(i+1)%6]],[top[i],bottom[i]]);return{atoms,edges}}
const hex=hexGeometry();
const models={
  sc:{system:'cubic',short:'Simple Cubic (SC)',title:'Simple Cubic',description:'Atoms occupy only the eight corners of the cube.',atoms:cubeCorners(),edges:cubeEdges(),effective:'1',coordination:'6',touch:'Cube edge',packing:'52.4%',example:'Polonium',relation:'8 corners × ⅛ = 1 atom;  a = 2r',contactRadius:1},
  bcc:{system:'cubic',short:'Body-Centred Cubic (BCC)',title:'Body-Centred Cubic',description:'One atom lies completely inside the cube in addition to the eight corner atoms.',atoms:[...cubeCorners(),{p:[0,0,0],type:'body'}],edges:cubeEdges(),effective:'2',coordination:'8',touch:'Body diagonal',packing:'68.0%',example:'Na, K, α-Fe',relation:'8 × ⅛ + 1 = 2 atoms;  √3a = 4r',contactRadius:Math.sqrt(3)/2},
  fcc:{system:'cubic',short:'Face-Centred Cubic (FCC)',title:'Face-Centred Cubic',description:'Atoms occupy every corner and the centre of each of the six faces.',atoms:[...cubeCorners(),...faceAtoms],edges:cubeEdges(),effective:'4',coordination:'12',touch:'Face diagonal',packing:'74.0%',example:'Cu, Ag, Al',relation:'8 × ⅛ + 6 × ½ = 4 atoms;  √2a = 4r',contactRadius:Math.SQRT1_2},
  st:{system:'tetragonal',short:'Simple Tetragonal',title:'Simple Tetragonal',description:'A cube stretched or compressed along one axis, with atoms only at its corners.',atoms:cubeCorners(1.3),edges:cubeEdges(1.3),effective:'1',coordination:'6',touch:'a-axis',packing:'Depends on c/a',example:'TiO₂ lattice',relation:'a = b ≠ c;  α = β = γ = 90°'},
  bct:{system:'tetragonal',short:'Body-Centred Tetragonal',title:'Body-Centred Tetragonal',description:'A tetragonal cell with one additional atom at the body centre.',atoms:[...cubeCorners(1.3),{p:[0,0,0],type:'body'}],edges:cubeEdges(1.3),effective:'2',coordination:'Varies',touch:'Depends on c/a',packing:'Depends on c/a',example:'White tin',relation:'8 × ⅛ + 1 = 2 atoms;  a = b ≠ c'},
  hex:{system:'hexagonal',short:'Simple Hexagonal',title:'Simple Hexagonal',description:'Hexagonal layers are stacked directly above one another.',atoms:hex.atoms,edges:hex.edges,effective:'3',coordination:'8',touch:'Basal plane',packing:'60.5%',example:'Hexagonal layers',relation:'12 × ⅙ + 2 × ½ = 3;  γ = 120°'}
};
const order={cubic:['sc','bcc','fcc'],tetragonal:['st','bct'],hexagonal:['hex']};

const fccSites=[[0,0,0],[0,.5,.5],[.5,0,.5],[.5,.5,0]];
const conventional={
  sc:[[0,0,0],[1,0,0],[0,1,0],[0,0,1],[1,1,0],[1,0,1],[0,1,1],[1,1,1]],
  bcc:[[0,0,0],[1,0,0],[0,1,0],[0,0,1],[1,1,0],[1,0,1],[0,1,1],[1,1,1],[.5,.5,.5]],
  fcc:[[0,0,0],[1,0,0],[0,1,0],[0,0,1],[1,1,0],[1,0,1],[0,1,1],[1,1,1],[0,.5,.5],[1,.5,.5],[.5,0,.5],[.5,1,.5],[.5,.5,0],[.5,.5,1]]
};
const examples={
  po:{name:'Polonium',short:'Po · SC',title:'Polonium — Simple Cubic',description:'Polonium atoms occupy a simple-cubic lattice with one lattice point per primitive cell.',basis:conventional.sc.map(p=>({p,s:'Po'})),species:{Po:{color:C.po,label:'Po'}},effective:'1',coordination:'6',touch:'Cube edge',packing:'52.4%',relation:'A direct example of the simple-cubic structure.'},
  fe:{name:'α-Iron',short:'α-Fe · BCC',title:'α-Iron — BCC',description:'At room temperature, α-iron adopts a body-centred cubic arrangement.',basis:conventional.bcc.map(p=>({p,s:'Fe'})),species:{Fe:{color:C.fe,label:'Fe'}},effective:'2',coordination:'8',touch:'Body diagonal',packing:'68.0%',relation:'Corner Fe atoms and a body-centred Fe atom form the BCC lattice.'},
  cu:{name:'Copper',short:'Cu · FCC',title:'Copper — FCC',description:'Copper atoms form a face-centred cubic structure with close-packed layers.',basis:conventional.fcc.map(p=>({p,s:'Cu'})),species:{Cu:{color:C.cu,label:'Cu'}},effective:'4',coordination:'12',touch:'Face diagonal',packing:'74.0%',relation:'FCC is the most efficiently packed of the three cubic unit cells.'},
  nacl:{name:'Sodium chloride',short:'NaCl · rock salt',title:'NaCl — Rock-Salt Structure',description:'Cl⁻ forms an FCC array and Na⁺ occupies all octahedral sites. Each ion has coordination number 6.',basis:[...fccSites.map(p=>({p,s:'Cl'})),...[ [.5,0,0],[0,.5,0],[0,0,.5],[.5,.5,.5] ].map(p=>({p,s:'Na'}))],species:{Na:{color:C.na,label:'Na⁺'},Cl:{color:C.cl,label:'Cl⁻'}},effective:'4 Na⁺ + 4 Cl⁻',coordination:'6 : 6',touch:'Along ion contacts',packing:'Ionic structure',relation:'NaCl is FCC-based, not a body-centred cubic structure.'},
  cscl:{name:'Caesium chloride',short:'CsCl · 8:8',title:'CsCl — Caesium Chloride',description:'Cl⁻ occupies cube corners and Cs⁺ occupies the cube centre, giving 8:8 coordination.',basis:[...conventional.sc.map(p=>({p,s:'Cl'})),{p:[.5,.5,.5],s:'Cs'}],species:{Cs:{color:C.cs,label:'Cs⁺'},Cl:{color:C.cl,label:'Cl⁻'}},effective:'1 Cs⁺ + 1 Cl⁻',coordination:'8 : 8',touch:'Body diagonal',packing:'Ionic structure',relation:'It resembles BCC geometrically, but is not a BCC Bravais lattice because the two sites contain different ions.'},
  zns:{name:'Zinc sulphide',short:'ZnS · zinc blende',title:'ZnS — Zinc-Blende Structure',description:'S²⁻ forms an FCC array and Zn²⁺ occupies half of the tetrahedral sites.',basis:[...fccSites.map(p=>({p,s:'S'})),...[ [.25,.25,.25],[.25,.75,.75],[.75,.25,.75],[.75,.75,.25] ].map(p=>({p,s:'Zn'}))],species:{Zn:{color:C.zn,label:'Zn²⁺'},S:{color:C.s,label:'S²⁻'}},effective:'4 Zn²⁺ + 4 S²⁻',coordination:'4 : 4',touch:'Tetrahedral contacts',packing:'FCC-based',relation:'Half of the eight tetrahedral holes in the FCC anion array are occupied.'}
};

let key='sc',mode='unit',viewMode='framework',voidType='coordination',exampleKey='nacl',repeat=2;
let rx=-.38,ry=.58,zoom=1,drag=false,last=[0,0],down=[0,0],building=false,placed=0,hoverTarget=null,raf=0,assembly=100,assemblyStart=0;

function shade(hex,f){const n=parseInt(hex.slice(1),16);return`rgb(${Math.round((n>>16)*f)},${Math.round(((n>>8)&255)*f)},${Math.round((n&255)*f)})`}
function rotate(p){let[x,y,z]=p,cy=Math.cos(ry),sy=Math.sin(ry),x1=x*cy+z*sy,z1=-x*sy+z*cy,cx=Math.cos(rx),sx=Math.sin(rx);return[x1,y*cx-z1*sx,y*sx+z1*cx]}
function project(p,sceneScale=1){const r=rotate(p),rect=viewer.getBoundingClientRect(),unit=Math.min(rect.width,rect.height)*.245*zoom*sceneScale,depth=1+r[2]*.085;return{x:rect.width/2+r[0]*unit*depth,y:rect.height/2-r[1]*unit*depth,z:r[2],scale:depth,unit}}
function drawLine(a,b,color='rgba(48,65,91,.68)',width=2,sceneScale=1,dash=[]){const p=project(a,sceneScale),q=project(b,sceneScale);ctx.save();ctx.beginPath();ctx.setLineDash(dash);ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke();ctx.restore()}
function drawEdges(edges,sceneScale=1,color='rgba(48,65,91,.68)'){edges.map(e=>{const a=project(e[0],sceneScale),b=project(e[1],sceneScale);return{e,z:(a.z+b.z)/2}}).sort((a,b)=>a.z-b.z).forEach(o=>drawLine(o.e[0],o.e[1],color,2.1,sceneScale))}
function sphere(atom,index=0,opts={}){const q=project(opts.p||atom.p,opts.sceneScale||1),base=(atom.type==='body'?25:atom.type==='face'?23:21)*(+$('size').value/92),rad=Math.max(7,opts.radiusWorld?opts.radiusWorld*q.unit*q.scale:base*q.scale),color=opts.color||C[atom.type]||C.corner,g=ctx.createRadialGradient(q.x-rad*.35,q.y-rad*.35,2,q.x,q.y,rad);g.addColorStop(0,'#fff');g.addColorStop(.18,color);g.addColorStop(1,shade(color,.48));ctx.save();ctx.globalAlpha=opts.alpha??1;if(opts.ghost){ctx.globalAlpha=.32+.18*Math.sin(performance.now()/180);ctx.setLineDash([5,4])}ctx.beginPath();ctx.arc(q.x,q.y,rad,0,Math.PI*2);ctx.fillStyle=g;ctx.fill();ctx.lineWidth=opts.ghost?4:1.6;ctx.strokeStyle=opts.ghost?'#ffc928':'rgba(22,35,55,.65)';ctx.stroke();ctx.restore();const label=opts.label||(atom.type==='corner'?'C':atom.type==='face'?'F':'B');if((opts.forceLabel||$('labels').checked)&&!opts.ghost){ctx.fillStyle=opts.labelColor||'#fff';ctx.font=`bold ${Math.max(10,Math.min(14,rad*.55))}px Arial`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(label,q.x,q.y)}return{...q,rad,index}}
function resizeCanvas(){const rect=viewer.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2),w=Math.round(rect.width*dpr),h=Math.round(rect.height*dpr);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,rect.width,rect.height)}

function drawUnit(){const m=models[key],space=mode==='packing'&&viewMode==='space',gap=1+(1-assembly/100)*.72;$('modelName').textContent=mode==='packing'?`${m.short} · ${space?'Space-filling':'Framework'}`:m.short;if($('edges').checked)drawEdges(m.edges,1,space?'rgba(48,65,91,.38)':'rgba(48,65,91,.68)');const source=mode==='unit'&&building?m.atoms.slice(0,placed):m.atoms;source.map((a,i)=>{const p=space?a.p.map(v=>v*gap):a.p;return{a,i,p,z:project(p).z}}).sort((a,b)=>a.z-b.z).forEach(o=>sphere(o.a,o.i,{p:o.p,radiusWorld:space?m.contactRadius:null,alpha:space?.96:1}));hoverTarget=null;if(mode==='unit'&&building&&placed<m.atoms.length)hoverTarget=sphere(m.atoms[placed],placed,{ghost:true})}

function coordinationVectors(k){if(k==='sc')return[[1,0,0],[-1,0,0],[0,1,0],[0,-1,0],[0,0,1],[0,0,-1]];if(k==='bcc')return[-1,1].flatMap(x=>[-1,1].flatMap(y=>[-1,1].map(z=>[x*.68,y*.68,z*.68])));const v=[];for(const zero of [0,1,2])for(const a of [-1,1])for(const b of [-1,1]){const p=[0,0,0];p[(zero+1)%3]=a*.78;p[(zero+2)%3]=b*.78;v.push(p)}return v}
function siteGeometry(k,type){if(k==='sc')return type==='cubic'?{name:'Cubic void',site:[0,0,0],neighbors:cubeCorners().map(a=>a.p),count:'1 cubic void per unit cell',cn:8}:null;if(k==='bcc'&&type==='tetra')return{name:'Distorted tetrahedral site',site:[0,-.5,-1],neighbors:[[-1,-1,-1],[1,-1,-1],[0,0,0],[0,0,-2]],count:'12 tetrahedral sites per unit cell',cn:4};if(k==='bcc'&&type==='octa')return{name:'Distorted octahedral site',site:[0,0,-1],neighbors:[[0,0,0],[0,0,-2],[-1,-1,-1],[-1,1,-1],[1,-1,-1],[1,1,-1]],count:'6 octahedral sites per unit cell',cn:6};if(k==='fcc'&&type==='tetra')return{name:'Tetrahedral void',site:[-.5,-.5,-.5],neighbors:[[-1,-1,-1],[0,0,-1],[0,-1,0],[-1,0,0]],count:'8 tetrahedral voids per unit cell',cn:4};if(k==='fcc'&&type==='octa')return{name:'Octahedral void',site:[0,0,0],neighbors:faceAtoms.map(a=>a.p),count:'4 octahedral voids per unit cell',cn:6};return null}
function drawCoordination(){const vectors=coordinationVectors(key);if($('voidLines').checked)vectors.forEach(p=>drawLine([0,0,0],p,'rgba(124,58,237,.58)',1.8,1));vectors.map((p,i)=>({p,i,z:project(p).z})).sort((a,b)=>a.z-b.z).forEach(o=>sphere({p:o.p,type:'corner'},o.i,{color:C.neighbor,forceLabel:$('voidLabels').checked,label:'N',alpha:.94}));sphere({p:[0,0,0],type:'body'},0,{color:C.central,forceLabel:$('voidLabels').checked,label:'A',labelColor:'#372400'});$('modelName').textContent=`${models[key].short} · Coordination ${models[key].coordination}`}
function drawVoid(){if(voidType==='coordination'){drawCoordination();return}const data=siteGeometry(key,voidType);if(!data){drawCoordination();return}const m=models[key];if($('edges').checked)drawEdges(m.edges,1,'rgba(48,65,91,.38)');m.atoms.map((a,i)=>({a,i,z:project(a.p).z})).sort((a,b)=>a.z-b.z).forEach(o=>sphere(o.a,o.i,{alpha:.2}));if($('voidLines').checked)data.neighbors.forEach(p=>drawLine(data.site,p,'rgba(124,58,237,.72)',1.9,1,[5,4]));data.neighbors.map((p,i)=>({p,i,z:project(p).z})).sort((a,b)=>a.z-b.z).forEach(o=>sphere({p:o.p,type:'corner'},o.i,{color:C.neighbor,alpha:.92,forceLabel:$('voidLabels').checked,label:'A'}));sphere({p:data.site,type:'body'},0,{color:C.void,radiusWorld:.14,forceLabel:$('voidLabels').checked,label:'V'});$('modelName').textContent=`${models[key].short} · ${data.name}`}

function latticeAtoms(ex,n){const map=new Map();for(let i=0;i<n;i++)for(let j=0;j<n;j++)for(let k=0;k<n;k++)for(const atom of ex.basis){const raw=[atom.p[0]+i,atom.p[1]+j,atom.p[2]+k],id=raw.map(v=>v.toFixed(3)).join('|')+'|'+atom.s;if(!map.has(id)){const p=raw.map(v=>(v/n-.5)*2.6);map.set(id,{p,s:atom.s,type:'corner'})}}return[...map.values()]}
function drawLattice(){const ex=examples[exampleKey],atoms=latticeAtoms(ex,repeat),box=cubeEdges(1.3);if($('edges').checked)drawEdges(box,1,'rgba(48,65,91,.35)');atoms.map((a,i)=>({a,i,z:project(a.p).z})).sort((a,b)=>a.z-b.z).forEach(o=>{const spec=ex.species[o.a.s];sphere(o.a,o.i,{color:spec.color,label:spec.label,forceLabel:$('labels').checked,alpha:.96})});$('modelName').textContent=`${ex.title} · ${repeat} × ${repeat} × ${repeat}`}

function draw(){resizeCanvas();if(assemblyStart){const elapsed=performance.now()-assemblyStart,reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;assembly=reduce?100:Math.min(100,elapsed/1800*100);$('assembly').value=Math.round(assembly);setAssemblyLabel();if(assembly>=100)assemblyStart=0}if(mode==='lattice')drawLattice();else if(mode==='voids')drawVoid();else drawUnit();if($('autoRotate').checked&&!drag)ry+=.006;raf=requestAnimationFrame(draw)}

function setInfo(source){for(const id of ['title','description','effective','coordination','touch','packing','example','relation'])$(id).textContent=source[id]??'—'}
function modelInfo(){const m=models[key];setInfo(m);if(mode==='packing')$('description').textContent=`Compare the guide framework with equal spheres approaching their contact positions in ${m.title}.`;if(mode==='voids')updateVoidInfo()}
function updateVoidInfo(){const m=models[key];if(voidType==='coordination'){$('title').textContent=`${m.title} coordination shell`;$('description').textContent='The gold reference atom is surrounded by its nearest neighbours. Rotate and count the highlighted neighbours.';$('effective').textContent=m.effective;$('coordination').textContent=m.coordination;$('touch').textContent='Nearest neighbours';$('packing').textContent=m.packing;$('example').textContent=m.example;$('relation').textContent=`One reference atom + ${m.coordination} nearest neighbours.`;return}const d=siteGeometry(key,voidType);if(!d)return;$('title').textContent=d.name;$('description').textContent='The purple marker is the interstitial site; highlighted atoms form its surrounding coordination geometry.';$('effective').textContent=d.count;$('coordination').textContent=d.cn;$('touch').textContent='Void neighbours';$('packing').textContent=models[key].packing;$('example').textContent=models[key].title;$('relation').textContent=d.count}
function setLegend(items){$('legend').innerHTML=items.map(x=>`<span><i class="dot" style="background:${x.color}"></i>${x.label}</span>`).join('')}
function defaultLegend(){setLegend([{color:C.corner,label:'Corner atom'},{color:C.face,label:'Face atom'},{color:C.body,label:'Body atom'}])}
function structureButtons(keys){$('cellList').innerHTML=keys.map(k=>`<button class="cell-btn${k===key?' active':''}" data-key="${k}">${models[k].short}</button>`).join('');$('cellList').querySelectorAll('button').forEach(b=>b.onclick=()=>setModel(b.dataset.key))}
function setModel(k){key=k;building=false;placed=0;$('progressWrap').classList.remove('show');$('buildTip').classList.remove('show');$('nextBtn').disabled=true;structureButtons(mode==='unit'?order[models[k].system]:order.cubic);document.querySelectorAll('.cell-btn').forEach(b=>b.classList.toggle('active',b.dataset.key===k));modelInfo();configureVoids();updateModeMessage()}
function showSystem(s){document.querySelectorAll('.systems button').forEach(b=>b.classList.toggle('active',b.dataset.system===s));key=order[s][0];structureButtons(order[s]);setModel(key)}
function setMode(next){mode=next;building=false;assemblyStart=0;document.querySelectorAll('#modeTabs button').forEach(b=>{const on=b.dataset.mode===mode;b.classList.toggle('active',on);b.setAttribute('aria-pressed',on)});document.querySelectorAll('.mode-panel').forEach(p=>p.classList.toggle('hidden',p.dataset.panel!==mode));$('systems').classList.toggle('hidden',mode!=='unit');$('cellChooser').classList.toggle('hidden',mode==='lattice');if((mode==='packing'||mode==='voids')&&!['sc','bcc','fcc'].includes(key))key='sc';if(mode!=='lattice')structureButtons(mode==='unit'?order[models[key].system]:order.cubic);if(mode==='lattice'){renderExamples();setInfo({...examples[exampleKey],example:examples[exampleKey].name});setLegend(Object.values(examples[exampleKey].species).map(s=>({color:s.color,label:s.label})))}else{defaultLegend();modelInfo()}configureVoids();updateModeMessage();updateScienceNote();updateControlState()}
function updateScienceNote(){if(mode==='unit')$('scienceNote').textContent='The lines are unit-cell guides, not chemical bonds.';else if(mode==='packing')$('scienceNote').textContent='Space-filling mode represents touching equal spheres; the framework view is a geometric guide.';else if(mode==='voids')$('scienceNote').textContent=key==='sc'?'Simple cubic has a central cubic void; it does not contain regular tetrahedral or octahedral voids.':'BCC interstitial sites are distorted; FCC has regular tetrahedral and octahedral voids.';else $('scienceNote').textContent=exampleKey==='nacl'?'NaCl is FCC-based: Cl⁻ forms the FCC array and Na⁺ fills octahedral sites.':exampleKey==='cscl'?'CsCl resembles a body-centred arrangement but is not a BCC Bravais lattice because the two sites contain different ions.':'A lattice is generated by repeating the selected unit cell in three dimensions.'}
function updateModeMessage(){if(mode==='unit')$('message').textContent='Select a model, then rotate it to inspect every atom position.';else if(mode==='packing')$('message').textContent=`Switch to Space-filling, then move the Assembly slider to see atoms approach contact along the ${models[key].touch.toLowerCase()}.`;else if(mode==='voids')$('message').textContent=voidType==='coordination'?`Count the ${models[key].coordination} highlighted nearest neighbours.`:(siteGeometry(key,voidType)?.count||'Choose an available void type.');else $('message').textContent='Change the lattice size to see how one repeating unit produces an extended crystal.'}
function setAssemblyLabel(){const value=Math.round(assembly);$('assemblyValue').textContent=value===100?'Contact':value===0?'Separated':`${value}% assembled`}
function configureVoids(){if(mode!=='voids')return;const allowed=key==='sc'?['coordination','cubic']:['coordination','tetra','octa'];document.querySelectorAll('#voidButtons button').forEach(b=>{b.disabled=!allowed.includes(b.dataset.void);b.classList.toggle('active',b.dataset.void===voidType)});if(!allowed.includes(voidType))voidType='coordination';document.querySelectorAll('#voidButtons button').forEach(b=>b.classList.toggle('active',b.dataset.void===voidType));updateVoidInfo();updateScienceNote()}
function renderExamples(){$('exampleList').innerHTML=Object.entries(examples).map(([k,e])=>`<button class="example-btn${k===exampleKey?' active':''}" data-example="${k}">${e.short}</button>`).join('');$('exampleList').querySelectorAll('button').forEach(b=>b.onclick=()=>{exampleKey=b.dataset.example;renderExamples();setInfo({...examples[exampleKey],example:examples[exampleKey].name});setLegend(Object.values(examples[exampleKey].species).map(s=>({color:s.color,label:s.label})));updateScienceNote()})}
function updateControlState(){$('size').disabled=mode==='packing'&&viewMode==='space'}
function startBuild(){building=true;placed=0;$('progressWrap').classList.add('show');$('buildTip').classList.add('show');$('nextBtn').disabled=false;updateProgress();$('message').textContent='Begin with the highlighted '+models[key].atoms[0].type+' position.'}
function place(){const m=models[key];if(!building||placed>=m.atoms.length)return;const type=m.atoms[placed].type;placed++;updateProgress();if(placed===m.atoms.length){building=false;$('nextBtn').disabled=true;$('buildTip').classList.remove('show');$('message').textContent='Excellent! You completed the '+m.title+' unit cell.'}else $('message').textContent=`${type[0].toUpperCase()+type.slice(1)} atom placed. Next: ${m.atoms[placed].type} position.`}
function updateProgress(){const total=models[key].atoms.length;$('progressText').textContent=`${placed} / ${total}`;$('progressBar').style.width=(placed/total*100)+'%'}

document.querySelectorAll('#modeTabs button').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));
document.querySelectorAll('#systems button').forEach(b=>b.onclick=()=>showSystem(b.dataset.system));
document.querySelectorAll('#viewButtons button').forEach(b=>b.onclick=()=>{viewMode=b.dataset.view;document.querySelectorAll('#viewButtons button').forEach(x=>x.classList.toggle('active',x.dataset.view===viewMode));if(viewMode==='space')assembly=+$('assembly').value;updateControlState();updateScienceNote()});
document.querySelectorAll('#voidButtons button').forEach(b=>b.onclick=()=>{if(b.disabled)return;voidType=b.dataset.void;configureVoids();updateModeMessage()});
$('assembly').oninput=e=>{assembly=+e.target.value;assemblyStart=0;if(viewMode!=='space'){viewMode='space';document.querySelectorAll('#viewButtons button').forEach(x=>x.classList.toggle('active',x.dataset.view==='space'))}setAssemblyLabel();updateControlState()};
$('animateAssembly').onclick=()=>{viewMode='space';document.querySelectorAll('#viewButtons button').forEach(x=>x.classList.toggle('active',x.dataset.view==='space'));assembly=0;assemblyStart=performance.now();updateControlState()};
$('repeat').oninput=e=>{repeat=+e.target.value;$('repeatValue').textContent=`${repeat} × ${repeat} × ${repeat}`};
$('buildBtn').onclick=startBuild;$('nextBtn').onclick=place;$('revealBtn').onclick=()=>{building=false;placed=models[key].atoms.length;$('nextBtn').disabled=true;$('buildTip').classList.remove('show');$('progressWrap').classList.remove('show');$('message').textContent='Complete unit cell shown.'};
$('resetBtn').onclick=()=>{rx=-.38;ry=.58;zoom=1};

viewer.addEventListener('pointerdown',e=>{drag=true;last=down=[e.clientX,e.clientY];viewer.setPointerCapture(e.pointerId);viewer.classList.add('dragging')});
viewer.addEventListener('pointermove',e=>{if(!drag)return;ry+=(e.clientX-last[0])*.009;rx+=(e.clientY-last[1])*.009;rx=Math.max(-1.5,Math.min(1.5,rx));last=[e.clientX,e.clientY]});
viewer.addEventListener('pointerup',e=>{const moved=Math.hypot(e.clientX-down[0],e.clientY-down[1]);drag=false;viewer.classList.remove('dragging');if(mode==='unit'&&building&&hoverTarget&&moved<8){const r=viewer.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;if(Math.hypot(x-hoverTarget.x,y-hoverTarget.y)<hoverTarget.rad+18)place()}});
viewer.addEventListener('pointercancel',()=>{drag=false;viewer.classList.remove('dragging')});
viewer.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.58,Math.min(1.55,zoom-e.deltaY*.001))},{passive:false});

defaultLegend();showSystem('cubic');renderExamples();setAssemblyLabel();setMode('unit');draw();
window.addEventListener('pagehide',()=>cancelAnimationFrame(raf),{once:true});
})();
